# Generated by Django 4.0 on 2021-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowedBook', models.CharField(max_length=500)),
                ('memberBorrower', models.CharField(max_length=255)),
                ('fees', models.FloatField()),
                ('destination', models.BooleanField()),
            ],
        ),
    ]
